package zw.co.afrosoft.zdf.enums;


public enum PaymentType {
    SUBSCRIPTION, LOAN_REPAYMENT, PROJECT_REPAYMENT, SECURITY_REPAYMENT,
    SUBSCRIPTION_INTEREST, LOAN_INTEREST, PROJECT_INTEREST, CLAIM_PAYMENT,
    REVERSAL
}
